### ISSUE TITLE
On Edit Demand, if locationchooser isn't started causes application crash on submit

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#37]
java.lang.NullPointerException: Attempt to invoke virtual method 'double org.osmdroid.util.GeoPoint.getLatitude()' on a null object reference
            at neeedo.imimaprx.htw.de.neeedo.entities.util.Location.<init>(Location.java:27)
            at neeedo.imimaprx.htw.de.neeedo.fragments.FormDemandFragment.getLocation(FormDemandFragment.java:125)
            at neeedo.imimaprx.htw.de.neeedo.fragments.handler.SendDemandHandler.onClick(SendDemandHandler.java:43)

**Comment by TIIUNDER** [comment]
This will be handled by form validation. For Demands it already works. https://github.com/neeedo/neeedo-android/issues/16
