### ISSUE TITLE
Edit demand change price causes application crash 

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#44]
07-23 12:13:52.152  30454-30454/neeedo.imimaprx.htw.de.neeedo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: neeedo.imimaprx.htw.de.neeedo, PID: 30454
    java.lang.NumberFormatException: Invalid double: "90,00"
            at java.lang.StringToReal.invalidReal(StringToReal.java:63)
            at java.lang.StringToReal.initialParse(StringToReal.java:164)
            at java.lang.StringToReal.parseDouble(StringToReal.java:282)
            at java.lang.Double.parseDouble(Double.java:301)
            at neeedo.imimaprx.htw.de.neeedo.fragments.FormDemandFragment.getPrice(FormDemandFragment.java:130)
            at neeedo.imimaprx.htw.de.neeedo.fragments.handler.SendDemandHandler.onClick(SendDemandHandler.java:45)
            at android.view.View.performClick(View.java:5230)
            at android.view.View$PerformClick.run(View.java:20999)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by TIIUNDER** [comment]
Fixed by https://github.com/neeedo/neeedo-android/commit/ed8c7a1390ae9401bf8bbe10e9f11ab67c498a30
