### ISSUE TITLE
Create offer fails on serveral actions, causes application crash 

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-android#48]
07-24 10:57:23.101  17356-17691/neeedo.imimaprx.htw.de.neeedo E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #9
    Process: neeedo.imimaprx.htw.de.neeedo, PID: 17356
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 47775756 byte allocation with 16777120 free bytes and 44MB until OOM
            at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:843)
            at neeedo.imimaprx.htw.de.neeedo.utils.ImageUtils.rotateBitmap(ImageUtils.java:37)
            at neeedo.imimaprx.htw.de.neeedo.fragments.handler.ImageUploadHandler.getFileInputStream(ImageUploadHandler.java:159)
            at neeedo.imimaprx.htw.de.neeedo.fragments.handler.ImageUploadHandler.doInBackground(ImageUploadHandler.java:106)
            at neeedo.imimaprx.htw.de.neeedo.fragments.handler.ImageUploadHandler.doInBackground(ImageUploadHandler.java:35)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-24 10:57:23.641  17356-17356/neeedo.imimaprx.htw.de.neeedo E/WindowManager﹕ android.view.WindowLeaked: Activity neeedo.imimaprx.htw.de.neeedo.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{1ba988f6 V.E..... R.....I. 0,0-684,321} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:479)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:277)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:312)
            at neeedo.imimaprx.htw.de.neeedo.fragments.handler.ImageUploadHandler.onPreExecute(ImageUploadHandler.java:62)
            at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
            at android.os.AsyncTask.execute(AsyncTask.java:535)
            at neeedo.imimaprx.htw.de.neeedo.fragments.FormOfferFragment.onActivityResult(FormOfferFragment.java:150)
            at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:163)
            at android.app.Activity.dispatchActivityResult(Activity.java:6632)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:4169)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:4216)
            at android.app.ActivityThread.access$1400(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6117)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by stephanlindauer** [comment]
please add information on how to reproduce this bug @GammaG

**Comment by GammaG** [comment]
wasn't able to reproduce it.
