### ISSUE TITLE
Adding favorites in swiper doesn't work

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#63]
If I swipe a card to the right, I get an "unknown error" toast message and 400 bad request error in log.

`07-25 11:31:57.230    1830-1872/neeedo.imimaprx.htw.de.neeedo W/RestTemplate﹕ POST request for "https://10.0.2.2:9443/favorites" resulted in 400 (Bad Request); invoking error handler
07-25 11:31:57.230    1830-1872/neeedo.imimaprx.htw.de.neeedo E/CreateFavoriteAsyncTask﹕ 400 Bad Request
    org.springframework.web.client.HttpClientErrorException: 400 Bad Request
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
            at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:590)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:504)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:452)
            at neeedo.imimaprx.htw.de.neeedo.rest.favorites.CreateFavoriteAsyncTask.doInBackground(CreateFavoriteAsyncTask.java:62)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)`

**Comment by GammaG** [comment]
I fixed that
