### ISSUE TITLE
App crashes if I get back to demand swiper view from edit view

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#70]
Please check this screencast to reproduce the issue: https://dl.dropboxusercontent.com/u/17564871/android_demand_swiper_crash.mp4

`07-26 03:17:01.899    3099-3099/neeedo.imimaprx.htw.de.neeedo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: neeedo.imimaprx.htw.de.neeedo, PID: 3099
    java.lang.RuntimeException: Could not dispatch event: class neeedo.imimaprx.htw.de.neeedo.events.FoundMatchesEvent to handler [EventHandler public void neeedo.imimaprx.htw.de.neeedo.fragments.SingleDemandFragmentSwiper.handleFoundMatchesEvent(neeedo.imimaprx.htw.de.neeedo.events.FoundMatchesEvent)]: Attempt to invoke virtual method 'java.util.ArrayList neeedo.imimaprx.htw.de.neeedo.entities.demand.Demand.getMatchingOfferList()' on a null object reference
            at com.squareup.otto.Bus.throwRuntimeException(Bus.java:458)
            at com.squareup.otto.Bus.dispatch(Bus.java:388)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
            at com.squareup.otto.Bus.post(Bus.java:338)
            at neeedo.imimaprx.htw.de.neeedo.service.EventService.post(EventService.java:21)
            at neeedo.imimaprx.htw.de.neeedo.rest.matching.GetOffersToDemandAsyncTask.onPostExecute(GetOffersToDemandAsyncTask.java:67)
            at android.os.AsyncTask.finish(AsyncTask.java:636)
            at android.os.AsyncTask.access$500(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList neeedo.imimaprx.htw.de.neeedo.entities.demand.Demand.getMatchingOfferList()' on a null object reference
            at neeedo.imimaprx.htw.de.neeedo.models.DemandsModel.getOfferlistToDemandById(DemandsModel.java:55)
            at neeedo.imimaprx.htw.de.neeedo.fragments.SingleDemandFragmentSwiper.handleFoundMatchesEvent(SingleDemandFragmentSwiper.java:79)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
            at com.squareup.otto.Bus.dispatch(Bus.java:386)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
            at com.squareup.otto.Bus.post(Bus.java:338)
            at neeedo.imimaprx.htw.de.neeedo.service.EventService.post(EventService.java:21)
            at neeedo.imimaprx.htw.de.neeedo.rest.matching.GetOffersToDemandAsyncTask.onPostExecute(GetOffersToDemandAsyncTask.java:67)
            at android.os.AsyncTask.finish(AsyncTask.java:636)
            at android.os.AsyncTask.access$500(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by stephanlindauer** [comment]
i think this is something @GammaG should look into...

here is my stacktrace

07-27 13:39:08.486  31679-31708/neeedo.imimaprx.htw.de.neeedo W/RestTemplate﹕ POST request for "https://api.neeedo.com/matching/demand" resulted in 400 (Bad Request); invoking error handler
07-27 13:39:08.487  31679-31708/neeedo.imimaprx.htw.de.neeedo E/GetOffersToDemandAsyncTask﹕ 400 Bad Request
    org.springframework.web.client.HttpClientErrorException: 400 Bad Request
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
            at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:590)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:504)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:452)
            at neeedo.imimaprx.htw.de.neeedo.rest.matching.GetOffersToDemandAsyncTask.doInBackground(GetOffersToDemandAsyncTask.java:51)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-27 13:39:08.504  31679-31679/neeedo.imimaprx.htw.de.neeedo D/AndroidRuntime﹕ Shutting down VM
07-27 13:39:08.507  31679-31679/neeedo.imimaprx.htw.de.neeedo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: neeedo.imimaprx.htw.de.neeedo, PID: 31679
    java.lang.RuntimeException: Could not dispatch event: class neeedo.imimaprx.htw.de.neeedo.events.FoundMatchesEvent to handler [EventHandler public void neeedo.imimaprx.htw.de.neeedo.fragments.SingleDemandFragmentSwiper.handleFoundMatchesEvent(neeedo.imimaprx.htw.de.neeedo.events.FoundMatchesEvent)]: Attempt to invoke virtual method 'java.util.ArrayList neeedo.imimaprx.htw.de.neeedo.entities.demand.Demand.getMatchingOfferList()' on a null object reference
            at com.squareup.otto.Bus.throwRuntimeException(Bus.java:458)
            at com.squareup.otto.Bus.dispatch(Bus.java:388)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
            at com.squareup.otto.Bus.post(Bus.java:338)
            at neeedo.imimaprx.htw.de.neeedo.service.EventService.post(EventService.java:21)
            at neeedo.imimaprx.htw.de.neeedo.rest.matching.GetOffersToDemandAsyncTask.onPostExecute(GetOffersToDemandAsyncTask.java:67)
            at android.os.AsyncTask.finish(AsyncTask.java:636)
            at android.os.AsyncTask.access$500(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList neeedo.imimaprx.htw.de.neeedo.entities.demand.Demand.getMatchingOfferList()' on a null object reference
            at neeedo.imimaprx.htw.de.neeedo.models.DemandsModel.getOfferlistToDemandById(DemandsModel.java:55)
            at neeedo.imimaprx.htw.de.neeedo.fragments.SingleDemandFragmentSwiper.handleFoundMatchesEvent(SingleDemandFragmentSwiper.java:95)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
            at com.squareup.otto.Bus.dispatch(Bus.java:386)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:369)
            at com.squareup.otto.Bus.post(Bus.java:338)
            at neeedo.imimaprx.htw.de.neeedo.service.EventService.post(EventService.java:21)
            at neeedo.imimaprx.htw.de.neeedo.rest.matching.GetOffersToDemandAsyncTask.onPostExecute(GetOffersToDemandAsyncTask.java:67)
            at android.os.AsyncTask.finish(AsyncTask.java:636)
            at android.os.AsyncTask.access$500(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-27 13:39:25.729  31679-31721/neeedo.imimaprx.htw.de.neeedo W/RestTemplate﹕ GET request for "https://api.neeedo.com/conversations/?read=false" resulted in 404 (Not Found); invoking error handler
07-27 13:39:25.730  31679-31721/neeedo.imimaprx.htw.de.neeedo E/GetMessagesByUserIdAndReadStateAsyncTask﹕ 404 Not Found
    org.springframework.web.client.HttpClientErrorException: 404 Not Found
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
            at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:590)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:504)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:452)
            at neeedo.imimaprx.htw.de.neeedo.rest.message.GetMessagesByUserIdAndReadStateAsyncTask.doInBackground(GetMessagesByUserIdAndReadStateAsyncTask.java:57)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-27 13:39:52.354  31679-31702/neeedo.imimaprx.htw.de.neeedo W/RestTemplate﹕ GET request for "https://api.neeedo.com/conversations/?read=false" resulted in 404 (Not Found); invoking error handler
07-27 13:39:52.357  31679-31702/neeedo.imimaprx.htw.de.neeedo E/GetMessagesByUserIdAndReadStateAsyncTask﹕ 404 Not Found
    org.springframework.web.client.HttpClientErrorException: 404 Not Found
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
            at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:590)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:504)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:452)
            at neeedo.imimaprx.htw.de.neeedo.rest.message.GetMessagesByUserIdAndReadStateAsyncTask.doInBackground(GetMessagesByUserIdAndReadStateAsyncTask.java:57)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-27 13:40:22.120  31679-31708/neeedo.imimaprx.htw.de.neeedo W/RestTemplate﹕ GET request for "https://api.neeedo.com/conversations/?read=false" resulted in 404 (Not Found); invoking error handler
07-27 13:40:22.123  31679-31708/neeedo.imimaprx.htw.de.neeedo E/GetMessagesByUserIdAndReadStateAsyncTask﹕ 404 Not Found
    org.springframework.web.client.HttpClientErrorException: 404 Not Found
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
            at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:590)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:546)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:504)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:452)
            at neeedo.imimaprx.htw.de.neeedo.rest.message.GetMessagesByUserIdAndReadStateAsyncTask.doInBackground(GetMessagesByUserIdAndReadStateAsyncTask.java:57)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by GammaG** [comment]
fixed
