### ISSUE TITLE
Confirming location in location chooser in demand form throws exception

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#78]
This App doesn't crash and the location is correct. But we get this error in the log. I think we had the same problem for demands, but there it works.

`07-27 13:29:45.141  10975-10987/neeedo.imimaprx.htw.de.neeedo I/art﹕ Background sticky concurrent mark sweep GC freed 3030(134KB) AllocSpace objects, 4(64KB) LOS objects, 0% free, 58MB/58MB, paused 8.932ms total 14.590ms
07-27 13:29:45.256  10975-10975/neeedo.imimaprx.htw.de.neeedo E/WindowManager﹕ android.view.WindowLeaked: Activity neeedo.imimaprx.htw.de.neeedo.LocationChooserActivity has leaked window android.widget.ZoomButtonsController$Container{3b7a3d66 V.E..... ........ 0,0-768,97} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
            at android.widget.ZoomButtonsController.setVisible(ZoomButtonsController.java:370)
            at org.osmdroid.views.MapView$MapViewGestureDetectorListener.onDown(MapView.java:1097)
            at android.view.GestureDetector.onTouchEvent(GestureDetector.java:550)
            at org.osmdroid.views.MapView.dispatchTouchEvent(MapView.java:758)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2049)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
            at android.view.View.dispatchPointerEvent(View.java:8666)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper.loop(Looper.java:122)
            at android.app.ActivityThre`

**Comment by stephanlindauer** [comment]
so when exactly does this happen? doesnt happen on my emulator or device
probable fix: http://stackoverflow.com/questions/27254570/android-view-windowleaked-activity-has-leaked-window-android-widget-zoombuttons

**Comment by stephanlindauer** [comment]
when hitting the "checked" symbol in the upper right of the location chooser?

**Comment by TIIUNDER** [comment]
Yes

**Comment by TIIUNDER** [comment]
It happens only in the Offer form, not in Demand form

**Comment by TIIUNDER** [comment]
SORRY! The other way around! in Demand form, not in offer form, sorry!

**Comment by stephanlindauer** [comment]
ok. thx.

**Comment by stephanlindauer** [comment]
still cant reproduce. can you check if my latest commit does the trick for you?

**Comment by TIIUNDER** [comment]
Yes, it works now for me

**Comment by stephanlindauer** [comment]
<3 osmdroid
