### ISSUE TITLE
App crashes on photo landscape 

### ISSUE THREAD

**Issue by TIIUNDER** [neeedo/neeedo-android#84]
It looks like there is a problem with the orientation of phone. 

`07-27 20:03:40.775  10527-10527/neeedo.imimaprx.htw.de.neeedo W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41ccdda0)
07-27 20:03:40.775  10527-10527/neeedo.imimaprx.htw.de.neeedo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: neeedo.imimaprx.htw.de.neeedo, PID: 10527
    java.lang.RuntimeException: Unable to start activity ComponentInfo{neeedo.imimaprx.htw.de.neeedo/neeedo.imimaprx.htw.de.neeedo.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2412)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4053)
            at android.app.ActivityThread.access$1000(ActivityThread.java:174)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5593)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:416)
            at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:451)
            at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:443)
            at neeedo.imimaprx.htw.de.neeedo.MainActivity.changeFragment(MainActivity.java:104)
            at neeedo.imimaprx.htw.de.neeedo.MainActivity.initOrRestoreState(MainActivity.java:98)
            at neeedo.imimaprx.htw.de.neeedo.MainActivity.onCreate(MainActivity.java:34)
            at android.app.Activity.performCreate(Activity.java:5458)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4053)
            at android.app.ActivityThread.access$1000(ActivityThread.java:174)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5593)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
07-27 20:03:43.038  10527-10527/neeedo.imimaprx.htw.de.neeedo I/Process﹕ Sending signal. PID: 10527 SIG: 9`

**Comment by stephanlindauer** [comment]
when and how?

**Comment by TIIUNDER** [comment]
I just try to take a photo in the create offer view. The problem is my phone, the camera just spins the rotation around ^^ Not sure why, but this can be a problem on other devices to

**Comment by TIIUNDER** [comment]
Please check this video I made
https://dl.dropboxusercontent.com/u/17564871/20150727_201252.mp4

**Comment by TIIUNDER** [comment]
This seems to strongly depend which photo app you are using.

**Comment by TIIUNDER** [comment]
Using an other photo app (OpenCamera) seems to avoid this bug, but it still should be fixed

**Comment by stephanlindauer** [comment]
i dont know if we can influence the behaviour of other apps. the weird thing is that you can see neeedo in horizontal mode before it crashes which should never happen due to the fact that set android:screenOrientation="portrait" in the manifest.

**Comment by TIIUNDER** [comment]
Yes, that's really strange. So we will need an orientation configuration f**\* Android fix

**Comment by stephanlindauer** [comment]
i am assuming that its destroyig the activity in the background and we dont properly restore state.

**Comment by stephanlindauer** [comment]
can you try again?

**Comment by stephanlindauer** [comment]
whats the name of the camera app you're using?

**Comment by TIIUNDER** [comment]
Still crashes. It's the dafault camera app of Samsung (Galaxy S4 Mini)

**Comment by stephanlindauer** [comment]
i am officially out of ideas

**Comment by stephanlindauer** [comment]
can you check again?

**Comment by stephanlindauer** [comment]
what happens if you breakpoint into the onCreateView onCreate and onViewStateRestored

**Comment by stephanlindauer** [comment]
lets just use the other app and close this ticket? @TIIUNDER

**Comment by TIIUNDER** [comment]
ok
